apiVersion: v1
kind: Service
metadata:
  name: calibre
  labels:
    app: calibre
spec:
  selector:
    app: calibre
  type: LoadBalancer
  ports:
  - name: calibregui
    port: 8889
    protocol: TCP
    targetPort: 8080
    nodePort:
  - name: calibreweb
    port: 8890
    protocol: TCP
    targetPort: 8081
    nodePort:
